---
version: "2.2"

services:

  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - ${ES_PATH}:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - tails_net


  # FSCrawler
  fs:
    container_name: fs
    image: dadoonet/fscrawler:2.10-SNAPSHOT
    #restart: always
    environment:
      - FS_JAVA_OPTS="-DLOG_LEVEL=debug -DDOC_LEVEL=debug"
    volumes:
      - ..\docs:/tmp/es:ro
      - ..\fsjobs:/root/.fscrawler
    depends_on:
      es:
        condition: service_healthy
    ports:
      - 8080:8080
        #command: try1 --restart --rest 
    entrypoint: ["/bin/bash", "-c", "sleep infinity"]
    networks:
      - tails_net

volumes:
  certs:
    driver: local
  esdata:
    driver: local
networks:
  tails_net:
    name: tails_net
    driver: bridge
